# Run Spec Tests
# https://github.com/puppetlabs/cat-github-actions/blob/main/.github/workflows/module_ci.yml
name: "Module CI"

on:
  push:

jobs:
  setup_matrix:
    name: "Setup Test Matrix"
    runs-on: ubuntu-latest
    outputs:
      spec_matrix: ${{ steps.get-matrix.outputs.spec_matrix }}

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v4"
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: "Setup ruby"
        uses: "ruby/setup-ruby@v1"
        with:
          ruby-version: "2.7"
          bundler-cache: true

      - name: "Bundle environment"
        run: |
          echo ::group::bundler environment
          bundle env
          echo ::endgroup::

      - name: Setup Spec Test Matrix
        id: get-matrix
        run: |
          bundle exec matrix_from_metadata_v2

  spec:
    name: "Spec tests (Puppet: ${{matrix.puppet_version}}, Ruby Ver: ${{matrix.ruby_version}})"
    needs: "setup_matrix"
    runs-on: ubunut-latest
    strategy:
      fail-fast: false
      matrix: ${{ fromJson( needs.setup_matrix.outputs.spec_matrix ) }}

    env:
      PUPPET_GEM_VERSION: ${{ matrix.puppet_version }}
      FACTER_GEM_VERSION: "https://github.com/puppetlabs/facter#main" # why is this set?

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v4"
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: "Setup ruby"
        uses: "ruby/setup-ruby@v1"
        with:
          ruby-version: ${{matrix.ruby_version}}
          bundler-cache: true

      - name: "Bundle environment"
        run: |
          echo ::group::bundler environment
          bundle env
          echo ::endgroup::

      - name: "Run Static & Syntax Tests"
        run: |
          bundle exec rake syntax lint metadata_lint check:symlinks check:git_ignore check:dot_underscore check:test_file rubocop
          bundle exec dependency-checker metadata.json

      - name: "Run tests"
        run: |
          bundle exec rake parallel_spec
